"""Initial migration

Revision ID: 5d32a530aeb3
Revises: 
Create Date: 2026-01-13 18:06:15.617075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5d32a530aeb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('allergen_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('texture_suitability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_age_months', sa.Integer(), nullable=False),
    sa.Column('is_choking_hazard', sa.Boolean(), nullable=False),
    sa.Column('safe_form_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_blocked_under_12m', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_is_blocked_under_12m'), 'food_items', ['is_blocked_under_12m'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=True)
    op.create_table('meal_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('baby_profile_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('plan_style', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('introduce_new_foods', sa.Boolean(), nullable=False),
    sa.Column('days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shopping_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prep_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_plans_baby_profile', 'meal_plans', ['baby_profile_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_baby_profile_id'), 'meal_plans', ['baby_profile_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_index('ix_meal_plans_user_start_date', 'meal_plans', ['user_id', 'start_date'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('texture_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergen_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_prep_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('min_age_months', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cuisine_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('safety_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_allergen_tags', 'recipes', ['allergen_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_is_vegetarian'), 'recipes', ['is_vegetarian'], unique=False)
    op.create_index('ix_recipes_tags', 'recipes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_recipes_texture_level'), 'recipes', ['texture_level'], unique=False)
    op.create_table('users',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('baby_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('feeding_style', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('dietary_preference', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cuisine_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avoid_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_prep_minutes', sa.Integer(), nullable=False),
    sa.Column('batch_cook_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pantry_staples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_baby_profiles_user_id')
    )
    op.create_index(op.f('ix_baby_profiles_id'), 'baby_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_baby_profiles_user_id'), 'baby_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baby_profiles_user_id'), table_name='baby_profiles')
    op.drop_index(op.f('ix_baby_profiles_id'), table_name='baby_profiles')
    op.drop_table('baby_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipes_texture_level'), table_name='recipes')
    op.drop_index('ix_recipes_tags', table_name='recipes', postgresql_using='gin')
    op.drop_index(op.f('ix_recipes_is_vegetarian'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index('ix_recipes_allergen_tags', table_name='recipes', postgresql_using='gin')
    op.drop_table('recipes')
    op.drop_index('ix_meal_plans_user_start_date', table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_baby_profile_id'), table_name='meal_plans')
    op.drop_index('ix_meal_plans_baby_profile', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_is_blocked_under_12m'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###

