"""add_meal_and_reaction_logs

Revision ID: d4483bdbd74b
Revises: 5d32a530aeb3
Create Date: 2026-01-13 18:18:35.344332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4483bdbd74b'
down_revision: Union[str, None] = '5d32a530aeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('baby_profile_id', sa.Uuid(), nullable=False),
    sa.Column('meal_plan_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_slot', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_logs_baby_profile_date', 'meal_logs', ['baby_profile_id', 'date'], unique=False)
    op.create_index(op.f('ix_meal_logs_baby_profile_id'), 'meal_logs', ['baby_profile_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_id'), 'meal_logs', ['id'], unique=False)
    op.create_index(op.f('ix_meal_logs_meal_plan_id'), 'meal_logs', ['meal_plan_id'], unique=False)
    op.create_index('ix_meal_logs_recipe', 'meal_logs', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_recipe_id'), 'meal_logs', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    op.create_table('reaction_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('baby_profile_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('suspected_food_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suspected_recipe_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_logs_baby_profile_id'), 'reaction_logs', ['baby_profile_id'], unique=False)
    op.create_index('ix_reaction_logs_baby_profile_occurred', 'reaction_logs', ['baby_profile_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_reaction_logs_id'), 'reaction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_reaction_logs_user_id'), 'reaction_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_logs_user_id'), table_name='reaction_logs')
    op.drop_index(op.f('ix_reaction_logs_id'), table_name='reaction_logs')
    op.drop_index('ix_reaction_logs_baby_profile_occurred', table_name='reaction_logs')
    op.drop_index(op.f('ix_reaction_logs_baby_profile_id'), table_name='reaction_logs')
    op.drop_table('reaction_logs')
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_recipe_id'), table_name='meal_logs')
    op.drop_index('ix_meal_logs_recipe', table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_meal_plan_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_baby_profile_id'), table_name='meal_logs')
    op.drop_index('ix_meal_logs_baby_profile_date', table_name='meal_logs')
    op.drop_table('meal_logs')
    # ### end Alembic commands ###

